ingress:
  host: ticketing.dev

services:
  auth:
    name: auth-srv
    port: 3000
  tickets:
    name: tickets-srv
    port: 3000
  orders:
    name: orders-srv
    port: 3000
  payments:
    name: payments-srv
    port: 3000
  client:
    name: client-srv
    port: 3000
