apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.auth.service.port }}
          env:
            - name: MONGO_URI
              value: "{{ .Values.auth.env.mongoUri }}"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.env.jwtKeySecretName }}
                  key: {{ .Values.auth.env.jwtKey }}
