apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: {{ .Values.expiration.replicaCount }}
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: "{{ .Values.expiration.image.repository }}:{{ .Values.expiration.image.tag }}"
          imagePullPolicy: {{ .Values.expiration.image.pullPolicy }}
          ports:
            - containerPort: 3000
