apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nats-depl
spec:
  replicas: {{ .Values.nats.replicaCount }}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
          args:
            - "-p"
            - "{{ .Values.nats.ports.clientPort }}"
            - "-m"
            - "{{ .Values.nats.ports.monitoringPort }}"
            - "-hbi"
            - "5s"
            - "-hbt"
            - "5s"
            - "-hbf"
            - "2"
            - "-SD"
            - "-cid"
            - "{{ .Values.nats.clusterId }}"