apiVersion: v1
kind: Service
metadata:
  name: nats-srv
  labels:
    app: nats
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.natsStreaming.ports.clientPort }}
      targetPort: {{ .Values.natsStreaming.ports.clientPort }}
  selector:
    app: nats
