apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-deployment
spec:
  replicas: {{ .Values.ordersMongo.replicaCount }}
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo
    spec:
      containers:
        - name: orders-mongo
          image: "{{ .Values.ordersMongo.image.repository }}:{{ .Values.ordersMongo.image.tag }}"
          imagePullPolicy: {{ .Values.ordersMongo.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ordersMongo.service.port }}
