apiVersion: v1
kind: Service
metadata:
  name: orders-srv
  labels:
    app: orders
spec:
  type: {{ .Values.orders.service.type }}
  ports:
    - port: {{ .Values.orders.service.port }}
      targetPort: {{ .Values.orders.service.targetPort }}
  selector:
    app: orders
