apiVersion: v1
kind: Service
metadata:
  name: payments-mongo-srv
  labels:
    app: payments-mongo
spec:
  type: {{ .Values.paymentsMongo.service.type }}
  ports:
    - port: {{ .Values.paymentsMongo.service.port }}
      targetPort: {{ .Values.paymentsMongo.service.targetPort }}
  selector:
    app: payments-mongo
