apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.tickets.name }}
  labels:
    app: tickets
spec:
  type: {{ .Values.tickets.service.type }}
  ports:
    - port: {{ .Values.tickets.service.port }}
      targetPort: {{ .Values.tickets.service.targetPort }}
  selector:
    app: tickets
