apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-depl
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: {{ .Values.nats.clientIdFieldPath }}
            - name: NATS_URL
              value: {{ .Values.nats.url }}
            - name: NATS_CLUSTER_ID
              value: {{ .Values.nats.clusterId }}
            - name: MONGO_URI
              value: {{ .Values.mongoUri }}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwtSecretName }}
                  key: {{ .Values.jwtSecretKey }}
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.stripeSecretName }}
                  key: {{ .Values.stripeSecretKey }}
