apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.auth.name }}
                port:
                  number: {{ .Values.services.auth.port }}
          - path: /api/tickets
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.tickets.name }}
                port:
                  number: {{ .Values.services.tickets.port }}
          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.orders.name }}
                port:
                  number: {{ .Values.services.orders.port }}
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.payments.name }}
                port:
                  number: {{ .Values.services.payments.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.client.name }}
                port:
                  number: {{ .Values.services.client.port }}
