apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-depl
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-p"
            - "{{ .Values.ports.clientPort }}"   # Correctly resolve the client port
            - "-m"
            - "{{ .Values.ports.monitoringPort }}" # Correctly resolve the monitoring port
            - "-hbi"
            - "5s"
            - "-hbt"
            - "5s"
            - "-hbf"
            - "2"
            - "-SD"
            - "-cid"
            - "ticketing"
