image:
  repository: nats-streaming
  tag: "0.17.0"
  pullPolicy: IfNotPresent

replicaCount: 1

ports:
  clientPort: 4222
  monitoringPort: 8222

args:
  - "-p"
  - "{{ .Values.ports.clientPort }}"
  - "-m"
  - "{{ .Values.ports.monitoringPort }}"
  - "-hbi"
  - "5s"
  - "-hbt"
  - "5s"
  - "-hbf"
  - "2"
  - "-SD"
  - "-cid"
  - "ticketing"
