apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-depl
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGO_URI
              value: {{ .Values.env.mongoUri }}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.jwtKeySecretName }}
                  key: {{ .Values.env.jwtKey }}
