apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-srv
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
